import {
    BookIcon,
    FamilyIcon,
    UserIcon,
    ScienceIcon,
    HistoryIcon,
    GlobeIcon,
    LightbulbIcon,
    StethoscopeIcon,
    PaletteIcon,
    GraphIcon,
    ComputerIcon,
    CookingIcon,
    ScissorsIcon,
    MasksIcon,
    CapIcon,
    GameIcon,
    LeafIcon,
    HeartIcon,
    HomeIcon,
    SmileIcon,
    GavelIcon,
    CalculatorIcon,
    MusicIcon,
    PawIcon,
    ColumnIcon,
    BuildingIcon,
    BrainIcon,
    TrophyIcon,
    NotebookIcon,
    MapIcon,
    HandcuffsIcon
  } from 'lucide-react-native';

  
  export const categoriesData = [
    { name: 'Fiction', slug: 'Fiction', displayNameTR: 'Kurgu', Icon: BookIcon },
    { name: 'Nonfiction', slug: 'Nonfiction', displayNameTR: 'Kurgu Dışı', Icon: BookIcon },
    { name: 'Juvenile Fiction', slug: 'Juvenile Fiction', displayNameTR: 'Çocuk Kurgu', Icon: FamilyIcon },
    { name: 'Juvenile Nonfiction', slug: 'Juvenile Nonfiction', displayNameTR: 'Çocuk Kurgu Dışı', Icon: FamilyIcon },
    { name: 'Biography & Autobiography', slug: 'Biography & Autobiography', displayNameTR: 'Biyografi & Otobiyografi', Icon: UserIcon },
    { name: 'Science', slug: 'Science', displayNameTR: 'Bilim', Icon: ScienceIcon },
    { name: 'History', slug: 'History', displayNameTR: 'Tarih', Icon: HistoryIcon },
    { name: 'Religion', slug: 'Religion', displayNameTR: 'Din', Icon: GlobeIcon },
    { name: 'Social Science', slug: 'Social Science', displayNameTR: 'Sosyal Bilimler', Icon: UserIcon },
    { name: 'Technology & Engineering', slug: 'Technology & Engineering', displayNameTR: 'Teknoloji & Mühendislik', Icon: LightbulbIcon },
    { name: 'Medical', slug: 'Medical', displayNameTR: 'Tıp', Icon: StethoscopeIcon },
    { name: 'Art', slug: 'Art', displayNameTR: 'Sanat', Icon: PaletteIcon },
    { name: 'Business & Economics', slug: 'Business & Economics', displayNameTR: 'İşletme & Ekonomi', Icon: GraphIcon },
    { name: 'Computers', slug: 'Computers', displayNameTR: 'Bilgisayarlar', Icon: ComputerIcon },
    { name: 'Cooking', slug: 'Cooking', displayNameTR: 'Yemek Kitapları', Icon: CookingIcon },
    { name: 'Crafts & Hobbies', slug: 'Crafts & Hobbies', displayNameTR: 'El Sanatları & Hobiler', Icon: ScissorsIcon },
    { name: 'Drama', slug: 'Drama', displayNameTR: 'Tiyatro', Icon: MasksIcon },
    { name: 'Education', slug: 'Education', displayNameTR: 'Eğitim', Icon: CapIcon },
    { name: 'Family & Relationships', slug: 'Family & Relationships', displayNameTR: 'Aile & İlişkiler', Icon: FamilyIcon },
    { name: 'Foreign Language Study', slug: 'Foreign Language Study', displayNameTR: 'Yabancı Dil Eğitimi', Icon: GlobeIcon },
    { name: 'Games', slug: 'Games', displayNameTR: 'Oyunlar', Icon: GameIcon },
    { name: 'Gardening', slug: 'Gardening', displayNameTR: 'Bahçecilik', Icon: LeafIcon },
    { name: 'Health & Fitness', slug: 'Health & Fitness', displayNameTR: 'Sağlık & Fitness', Icon: HeartIcon },
    { name: 'House & Home', slug: 'House & Home', displayNameTR: 'Ev & Yaşam', Icon: HomeIcon },
    { name: 'Humor', slug: 'Humor', displayNameTR: 'Mizah', Icon: SmileIcon },
    { name: 'Law', slug: 'Law', displayNameTR: 'Hukuk', Icon: GavelIcon },
    { name: 'Literary Criticism', slug: 'Literary Criticism', displayNameTR: 'Edebi Eleştiri', Icon: BookIcon },
    { name: 'Mathematics', slug: 'Mathematics', displayNameTR: 'Matematik', Icon: CalculatorIcon },
    { name: 'Music', slug: 'Music', displayNameTR: 'Müzik', Icon: MusicIcon },
    { name: 'Nature', slug: 'Nature', displayNameTR: 'Doğa', Icon: LeafIcon },
    { name: 'Performing Arts', slug: 'Performing Arts', displayNameTR: 'Sahne Sanatları', Icon: MasksIcon },
    { name: 'Pets', slug: 'Pets', displayNameTR: 'Evcil Hayvanlar', Icon: PawIcon },
    { name: 'Philosophy', slug: 'Philosophy', displayNameTR: 'Felsefe', Icon: ColumnIcon },
    { name: 'Poetry', slug: 'Poetry', displayNameTR: 'Şiir', Icon: BookIcon },
    { name: 'Political Science', slug: 'Political Science', displayNameTR: 'Siyaset Bilimi', Icon: BuildingIcon },
    { name: 'Psychology', slug: 'Psychology', displayNameTR: 'Psikoloji', Icon: BrainIcon },
    { name: 'Reference', slug: 'Reference', displayNameTR: 'Başvuru Kaynakları', Icon: BookIcon },
    { name: 'Sports & Recreation', slug: 'Sports & Recreation', displayNameTR: 'Spor & Rekreasyon', Icon: TrophyIcon },
    { name: 'Study Aids', slug: 'Study Aids', displayNameTR: 'Ders Çalışma Yardımcıları', Icon: NotebookIcon },
    { name: 'Travel', slug: 'Travel', displayNameTR: 'Seyahat', Icon: MapIcon },
    { name: 'True Crime', slug: 'True Crime', displayNameTR: 'Gerçek Suç Hikayeleri', Icon: HandcuffsIcon },
  ];
  